version: '3'

services:
  frontend_server:
    build: frontend_server/
    depends_on:
      - 'database'
      - 'api_server'
    ports: 
      - '3000:3000'
    stdin_open: true
    # networks:
    #   - backpack-network

  api_server:
    build: api_server/
    depends_on:
      - 'database'
    ports:
      - '3001:3001'
    # networks:
    #   - backpack-network

  database:
    build: database_server/
    restart: always
    environment:
      POSTGRES_USER: backpack
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: backpack
    # networks:
    #   - backpack-network
        
  # networks:
  #   weather-network:
  #     name: backpack-network