version: '3'

services:
  frontend_server:
    build: frontend_server/
    depends_on:
      - 'database_server'
      - 'api_server'
    ports: 
      - '3000:3000'
    stdin_open: true

  api_server:
    build: api_server/
    depends_on:
      - 'database_server'
    ports:
      - '3001:3001'

  database_server:
    image: postgres
    ports:
        - "5432:5432"
    volumes:
        - ./database_server/dataLoad.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        POSTGRES_PASSWORD: badPassword

